import json

d = {}

d["Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control."] = None  # 0
d["Life is like a play: it's not the length, but the excellence of the acting that matters."] = None  # 1
d["Luck is what happens when preparation meets opportunity."] = None  # 2
d["Difficulties strengthen the mind, as labor does the body."] = None  # 3
d["As is a tale, so is life: not how long it is, but how good it is, is what matters."] = None  # 4
d["No man is free who is not master of himself."] = None  # 5
d["If anyone tells you that a certain person speaks ill of you, do not make excuses about what is said of you but answer, \"He was ignorant of my other faults, else he would not have mentioned these alone."] = None  # 6
d["Don't explain your philosophy. Embody it."] = None  # 7
d["Non est ad astra mollis e terris via\" - \"There is no easy way from the earth to the stars"] = None  # 8
d["No man was ever wise by chance"] = None  # 9
d["The best ideas are common property"] = None  # 10
d["Know you not that a good man does nothing for appearance sake, but for the sake of having done right?"] = None  # 11
d["It is our attitude toward events, not events themselves, which we can control. Nothing is by its own nature calamitous -- even death is terrible only if we fear it."] = None  # 12
d["What really frightens and dismays us is not external events themselves, but the way in which we think about them. It is not things that disturb us, but our interpretation of their significance."] = None  # 13
d["Whoever is going to listen to the philosophers needs a considerable practice in listening."] = None  # 14
d["When a youth was giving himself airs in the Theatre and saying, 'I am wise, for I have conversed with many wise men,' Epictetus replied, 'I too have conversed with many rich men, yet I am not rich!’."] = None  # 15
d["When any person harms you, or speaks badly of you, remember that he acts or speaks from a supposition of its being his duty. Now, it is not possible that he should follow what appears right to you, but what appears so to himself. Therefore, if he judges from a wrong appearance, he is the person hurt, since he too is the person deceived. For if anyone should suppose a true proposition to be false, the proposition is not hurt, but he who is deceived about it. Setting out, then, from these principles, you will meekly bear a person who reviles you, for you will say upon every occasion, \"It seemed so to him.\"...."] = None  # 16
d["Wherever there is a human being, there is an opportunity for crisis."] = None  # 17
d["As a man, casting off worn out garments taketh new ones, so the dweller in the body, entereth into ones that are new."] = None  # 18
d["Philosophy does not promise to secure anything external for man, otherwise it would be admitting something that lies beyond its proper subject-matter. For as the material of the carpenter is wood, and that of statuary bronze, so the subject-matter of the art of living is each person's own life."] = None  # 19
d["Nothing, to my way of thinking, is a better proof of a well ordered mind than a man’s ability to stop just where he is and pass some time in his own company."] = None  # 20
d["On Epicurus; He says: \"Contended poverty is an honourable estate.\" Indeed, if it is contented, it is not poverty at all. It is not the man who has little, but the man who craves more, that is poor."] = None  # 21
d["Amintirea plăcerilor este mai de durată și mai de încredere decât prezența lor."] = None  # 22
d["You have the power to strip away many superfluous troubles located wholly in your judgement, and to possess a large room for yourself embracing in thought the whole cosmos, to consider everlasting time, to think of the rapid change in the parts of each thing, of how short it is from birth until dissolution, and how the void before birth and that after dissolution are equally infinite."] = None  # 23
d["errare humanum est, sed perseverare diabolicum: 'to err is human, but to persist (in the mistake) is diabolical."] = None  # 24
d["I am not a ‘wise man,’ nor . . . shall I ever be. And so require not from me that I should be equal to the best, but that I should be better than the wicked. It is enough for me if every day I reduce the number of my vices, and blame my mistakes."] = None  # 25
d["It is much better to die of hunger unhindered by grief and fear than to live affluently beset with worry, dread, suspicion and unchecked desire."] = None  # 26
d["Huius (sapientis) opus unum est de divinis humanisque verum invenire; ab hac numquam recedit religio, pietas, iustitia ..."] = None  # 27
d["True happiness is to enjoy the present, without anxious dependence upon the future, not to amuse ourselves with either hopes or fears but to rest satisfied with what we have, which is sufficient, for he that is so wants nothing. The greatest blessings of mankind are within us and within our reach. A wise man is content with his lot, whatever it may be, without wishing for what he has not."] = None  # 28
d["no man is free until he s a master of himself!!"] = None  # 29
d["Wealth consists not in having great possessions, but in having few wants."] = None  # 30
d["There is only one way to happiness and that is to cease worrying about things which are beyond the power or our will."] = None  # 31
d["I must die. Must I then die lamenting? I must be put in chains. Must I then also lament? I must go into exile. Does any man then hinder me from going with smiles and cheerfulness and contentment?"] = None  # 32
d["The essence of philosophy is that a man should so live that his happiness shall depend as little as possible on external things."] = None  # 33
d["Concerning the Gods, there are those who deny the very existence of the Godhead; others say that it exists, but neither bestirs nor concerns itself not has forethought far anything. A third party attribute to it existence and forethought, but only for great and heavenly matters, not for anything that is on earth. A fourth party admit things on earth as well as in heaven, but only in general, and not with respect to each individual. A fifth, of whom were Ulysses and Socrates, are those that cry: --I move not without Thy knowledge!"] = None  # 34
d["If you wish to be a writer, write."] = None  # 35
d["When you enter a grove peopled with ancient trees, higher than the ordinary, and shutting out the sky with their thickly inter-twined branches, do not the stately shadows of the wood, the stillness of the place, and the awful gloom of this doomed cavern then strike you with the presence of a deity?"] = None  # 36
d["You only have to doze a moment, and all is lost. For ruin and salvation both have their source inside you."] = None  # 37
d["Only the educated are free."] = None  # 38
d["First say to yourself what you would beand then do what you have to do."] = None  # 39
d["The part of life we really live is small.' For all the rest of existence is not life, but merely time."] = None  # 40
d["It's not that we have little time, but more that we waste a good deal of it."] = None  # 41
d["Leisure without books is death, and burial of a man alive."] = None  # 42
d["distringit librorum multitudo (the abundance of books is distraction)"] = None  # 43
d["Men are not afraid of things, but of how they view them."] = None  # 44
d["f you wish to put off all worry, assume that what you fear may happen is certainly going to happen."] = None  # 45
d["How closely flattery resembles friendship! It not only apes friendship, but outdoes it, passing it in the race; with wide-open and indulgent ears it is welcomed and sinks to the depths of the heart, and it is pleasing precisely wherein it does harm."] = None  # 46
d["He who is brave is free"] = None  # 47
d["What you shun enduring yourself, attempt not to impose on others. You shun slavery- beware enslaving others! If you can endure to do that, one would think you had been once upon a time a slave yourself. For vice has nothing in common with virtue, nor Freedom with slavery."] = None  # 48
d["The final hour when we cease to exist does not itself bring death; it merely of itself completes the death-process. We reach death at that moment, but we have been a long time on the way."] = None  # 49
d["Death smiles at us all, all a man can do is smile back."] = None  # 50
d["It is quality rather than quantity that matters."] = None  # 51
d["It is not fit that I should give myself pain, for I have never intentionally given pain even to another."] = None  # 52
d["…because it is natural to touch more often the parts that hurt."] = None  # 53
d["Nothing has such power to broaden the mind as the ability to investigate systematically and truly all that comes under thy observation in life."] = None  # 54
d["Finally, everybody agrees that no one pursuit can be successfully followed by a man who is preoccupied with many things—eloquence cannot, nor the liberal studies—since the mind, when distracted, takes in nothing very deeply, but rejects everything that is, as it were, crammed into it. There is nothing the busy man is less busied with than living: there is nothing that is harder to learn."] = None  # 55
d["How good it is when you have roast meat or suchlike foods before you, to impress on your mind that this is the dead body of a fish, this is the dead body of a bird or pig; and again, that the Falernian wine is the mere juice of grapes, and your purple edged robe simply the hair of a sheep soaked in shell-fish blood!And in sexual intercourse that it is no more than the friction of a membrane and a spurt of mucus ejected. How good these perceptions are at getting to the heart of the real thing and penetrating through it, so you can see it for what it is!This should be your practice throughout all your life: when things have such a plausible appearance, show them naked, see their shoddiness, strip away their own boastful account of themselves.Vanity is the greatest seducer of reason: when you are most convinced that your work is important, that is when you are most under its spell."] = None  # 56
d["It takes the whole of life to learn how to live, and--what will perhaps make you wonder more--it takes the whole of life to learn how to die."] = None  # 57
d["The willing, Destiny guides them. The unwilling, Destiny drags them."] = None  # 58
d["Everything that happens, happens as it should, and if you observe carefully, you will find this to be so."] = None  # 59
d["How silly then to imagine that the human mind, which is formed of the same elements as divine beings, objects to movement and change of abode, while the divine nature finds delight and even self-preservation in continual and very rapid change."] = None  # 60
d["Love sometimes injures. Friendship always benefits, After friendship is formed you must trust, but before that you must judge."] = None  # 61
d["Love sometimes injures. Friendship always benefits"] = None  # 62
d["In the long run, every man will pay the penalty for his own misdeeds. The man who remembers this will be angry with no one, indignant with no one, revile no one, blame no one, offend no one, hate no one."] = None  # 63
d["Fire tests gold, suffering tests brave men."] = None  # 64
d["What need is there to weep over parts of life? The whole of it calls for tears."] = None  # 65
d["It is the sign of a weak mind to be unable to bear wealth."] = None  # 66
d["If a man knows not to which port he sails, no wind is favorable."] = None  # 67
d["All things fade into the storied past, and in a little while are shrouded in oblivion."] = None  # 68
d["The greatest loss of time is delay and expectation, which depend upon the future. We let go the present, which we have in our power, and look forward to that which depends upon chance, and so relinquish a certainty for an uncertainty."] = None  # 69
d["Sometimes even to live is an act of courage."] = None  # 70
d["Very little is needed for everything to be upset and ruined, only a slight lapse in reason."] = None  # 71
d["Nature does not reveal her mysteries once and for all."] = None  # 72
d["What need of prompt or hint when it is open to yourself to discern what needs to be done - and, if you can see your way, to follow it with kind but undeviating intent. If you cannot see the way, hold back and consult your best advisors. if some other factors obstruct this advice, proceed on your present resources, but with cautious deliberations, keeping always to what seems just. Justice is the best aim, as any failure is in fact a failure of justice.A man following reason in all things combines relaxation with initiative, spark with composure."] = None  # 73
d["You should always be ready to apply these two rules of action, the first, to do nothing other than what the kingly and law-making art ordains for the benefits of humankind, and, the second, to be prepared to change your mind if someone is at hand to put you right and guide you away from some groundless opinion."] = None  # 74
d["It is not the actions of others which trouble us (for those actions are controlled by their governing part), but rather it is our own judgments. Therefore remove those judgments and resolve to let go of your anger, and it will already be gone. How do you let go? By realizing that such actions are not shameful to you."] = None  # 75
d["That all is as thinking makes it so – and you control your thinking. So remove your judgements whenever you wish and then there is calm - as the sailor rounding the cape finds smooth water and the welcome of a waveless bay."] = None  # 76
d["Our thoughts is what our life make it"] = None  # 77
d["Do not act as if you were going to live ten thousand years. Death hangs over you. While you live, while it is in your power, be good."] = None  # 78
d["Our universe is a sorry little affair unless it has in it something for every age to investigate."] = None  # 79
d["The universe is flux, life is opinion."] = None  # 80
d["Live every day as if they last."] = None  # 81
d["It is impossible to begin to learn that which one thinks one already knows."] = None  # 82
d["It is not so much what happens to you as how you think about what happens.\" Epictetus"] = None  # 83
d["The world you see, nature's greatest and most glorious creation, and the human mind which gazes and wonders at it, and is the most splendid part of it, these are our own everlasting possessions and will remain with us as long as we ourselves remain. So, eager and upright, let us hasten with bold steps wherever circumstances take us, and let us journey through any countries whatever: there can be no place of exile within the world since nothing within the world is alien to men."] = None  # 84
d["How long are you going to wait before you demand the best for yourself and in no instance bypass the discriminations of reason? You have been given the principles that you ought to endorse, and you have endorsed them. What kind of teacher, then, are you still waiting for in order to refer your self-improvement to him? You are no longer a boy, but a full-grown man. If you are careless and lazy now and keep putting things off and always deferring the day after which you will attend to yourself, you will not notice that you are making no progress, but you will live and die as someone quite ordinary. From now on, then, resolve to live as a grown-up who is making progress, and make whatever you think best a law that you never set aside. And whenever you encounter anything that is difficult or pleasurable, or highly or lowly regarded, remember that the contest is now: you are at the Olympic Games, you cannot wait any longer, and that your progress is wrecked or preserved by a single day and a single event. That is how Socrates fulfilled himself by attending to nothing except reason in everything he encountered. And you, although you are not yet a Socrates, should live as someone who at least wants to be a Socrates."] = None  # 85
d["Sexual ecstasy is like death. It is one of the secrets of nature’s wisdom."] = None  # 86
d["Remember that all we have is “on loan” from Fortune, which can reclaim it without our permission—indeed, without even advance notice. Thus, we should love all our dear ones, but always with the thought that we have no promise that we may keep them forever—nay, no promise even that we may keep them for long."] = None  # 87
d["We are born under circumstances that would be favorable if we did not abandon them. It was nature's intention that there should be no need of great equipment for a good life: every individual can make himself happy."] = None  # 88
d["Time heals what reason cannot."] = None  # 89
d["Man is not worried by real problems so much as by his imagined anxieties about real problems"] = None  # 90
d["All the greatest blessings are a source of anxiety, and at no time should fortune be less trusted than when it is best; to maintain prosperity there is need of other prosperity, and in behalf of the prayers that have turned out well we must make still other prayers. For everything that comes to us from chance is unstable, and the higher it rises, the more liable it is to fall. Moreover, what is doomed to perish brings pleasure to no one; very wretched, therefore, and not merely short, must the life of those be who work hard to gain what they must work harder to keep. By great toil they attain what they wish, and with anxiety hold what they have attained; meanwhile they take no account of time that will never more return."] = None  # 91
d["You are unfortunate in my judgment, for you have never been unfortunate. You have passed through life with no antagonist to face you; no one will know what you were capable of, not even you yourself."] = None  # 92
d["Most powerful is he who has himself in his power."] = None  # 93
d["It is not that we have a short space of time, but that we waste much of it. Life is long enough, and it has been given in sufficiently generous measure to allow the accomplishment of the very greatest things if the whole of it is well invested. But when it is squandered in luxury and carelessness, when it is devoted to no good end, forced at last by the ultimate necessity we perceive that it has passed away before we were aware that it was passing."] = None  # 94
d["Nūllum magnum ingenium sine mixtūrā dēmentiae fuitNo great talent without an element of madness"] = None  # 95
d["We are members of one great body, planted by nature…. We must consider that we were born for the good of the whole"] = None  # 96
d["Religion is regarded by the common people as true, by the wise as false, and by rulers as useful."] = None  # 97
d["It's not because things are difficult that we dare not venture. It's because we dare not venture that they are difficult."] = None  # 98
d["And so when you see a man often wearing the robe of office, when you see one whose name is famous in the Forum, do not envy him; those things are bought at the price of life. They will waste all their years, in order that they may have one year reckoned by their name."] = None  # 99
d["There is nothing more shameful than perfidious friendship."] = None  # 100
d["...certain people have good, ordinary blood and others have an animated, lively sort of blood that comes to the face quickly."] = None  # 101
d["You may fetter my leg, but Zeus himself cannot get the better of my free will."] = None  # 102
d["Envy of other people shows how they are unhappy. Their continual attention to others behavior shows how they are boring."] = None  # 103
d["Reading should serve the goal of attaining peace; if it doesn’t make you peaceful, what good is it?"] = None  # 104
d["Life will follow the path it started upon, and will neither reverse nor check its course; it will make no noise, it will not remind you of its swiftness. Silent it will glide on; it will not prolong itself at the command of a king, or at the applause of the populace. Just as it was started on its first day, so it will run; nowhere will it turn aside, nowhere will it delay."] = None  # 105
d["Pain is slight if opinion has added nothing to it; ... in thinking it slight, you will make it slight. Everything depends on opinion. It is according to opinion that we suffer. A man is as wretched as he has convinced himself that he is."] = None  # 106
d["Nothing great is created suddenly  any more than a bunch of grapes or a fig. If you tell me that you desire a fig  I answer you that there must be time. Let it first blossom  then bear fruit  then ripen."] = None  # 107
d["Practice yourself  for heaven's sake  in little things  and thence proceed to greater."] = None  # 108
d["Ask not that events should happen as you will  but let your will be that events should happen as they do  and you shall have peace."] = None  # 109
d["Vex not thy spirit at the course of things  they heed not thy vexation. How ludicrous and outlandish is astonishment at anything that may happen in life."] = None  # 110
d["Here is a rule to remember when anything tempts you to feel bitter: not  \"This is a misfortune \" but \"To bear this worthily is good fortune.\""] = None  # 111
d["Adapt yourself to the things among which your lot has been cast and love sincerely the fellow creatures with whom destiny has ordained that you shall live."] = None  # 112
d["Love only what befalls you and is spun for you by fate."] = None  # 113
d["There is only one way to happiness  and that is to cease worrying about things which are beyond the power of our will."] = None  # 114
d["If thou workest at that which is before thee ... expecting nothing  fearing nothing  but satisfied with thy present activity according to Nature  and with heroic truth in every word and sound which thou utterest  thou wilt live happy. And there is no man who is able to prevent this."] = None  # 115
d["Night brings our troubles to the light rather than banishes them."] = None  # 116
d["No untroubled day has ever dawned for me."] = None  # 117
d["Nothing befalls a man except what is in his nature to endure."] = None  # 118
d["Difficulties are things that show what men are."] = None  # 119
d["It is not death that a man should fear  he should fear never beginning to live."] = None  # 120
d["It is not death or pain that is to be dreaded  but the fear of pain or death."] = None  # 121
d["All philosophy in two words  - sustain and abstain."] = None  # 122
d["If you are surprised at the number of our maladies  count our cooks."] = None  # 123
d["Why do we shrink from change? What can come into being save by change?"] = None  # 124
d["There is change in all things. You yourself are subject to continual change and some decay  and this is common to the entire universe."] = None  # 125
d["A man should remove not only unnecessary acts  but also unnecessary thoughts  for then superfluous activity will not follow."] = None  # 126
d["When I think over what I have said  I envy dumb people."] = None  # 127
d["Constant exposure to dangers will breed contempt for them."] = None  # 128
d["The first rule is to keep an untroubled spirit. The second is to look things in the face and know them for what they are."] = None  # 129
d["So when the crisis is upon you  remember that God  like a trainer of wrestlers  has matched you with a tough and stalwart antagonist... that you may prove a victor at the Great Games."] = None  # 130
d["All cruelty springs from weakness."] = None  # 131
d["There is no man so blessed that some who stand by his deathbed won't hail the occasion with delight."] = None  # 132
d["Time is like a river of fleeting events  and its current is strong  as soon as something comes into sight  it is swept past us  and something else takes its place  and that too will be swept away."] = None  # 133
d["No great thing is created suddenly  any more than a bunch of grapes or a fig. If you tell me that you desire a fig  I answer you that there must be time. Let it first blossom  then bear fruit  then ripen."] = None  # 134
d["Drunkenness is nothing but voluntary madness."] = None  # 135
d["He is a drunkard who takes more than three glasses  though he be not drunk."] = None  # 136
d["Consider how much more you often suffer from your anger and grief than from those very things for which you are angry and grieved."] = None  # 137
d["We are not troubled by things  but by the opinion which we have of things."] = None  # 138
d["If you are distressed by anything external  the pain is not due to the thing itself but to your own estimate of it  and this you have the power to revoke at any moment."] = None  # 139
d["Men are not influenced by things  but by their thoughts about things."] = None  # 140
d["On the occasion of every accident that befalls you ... inquire what power you have for turning it to use."] = None  # 141
d["What a great blessing is a friend with a heart so trusty you may safely bury all your secrets in it."] = None  # 142
d["Whatever the universal nature assigns to any man at any time is for the good of that man at that time."] = None  # 143
d["Fate rules the affairs of mankind with no recognizable order."] = None  # 144
d["A great step toward independence is a good-humoured stomach."] = None  # 145
d["He is a man of sense who does not grieve for what he has not  but rejoices in what he has."] = None  # 146
d["Take full account of the excellencies which you possess  and in gratitude remember how you would hanker after them  if you had them not."] = None  # 147
d["Freedom is not procured by a full enjoyment of what is desired  but by controlling the desire."] = None  # 148
d["Try to live the life of the good man who is more than content with what is allocated to him."] = None  # 149
d["Bear and forbear."] = None  # 150
d["The true worth of a man is to be measured by the objects he pursues."] = None  # 151
d["Without a purpose  nothing should be done."] = None  # 152
d["First say to yourself what you would be  and then do what you have to do."] = None  # 153
d["A man's worth is no greater than the worth of his ambitions."] = None  # 154
d["A man's happiness: to do the things proper to man."] = None  # 155
d["The one thing worth living for is to keep one's soul pure."] = None  # 156
d["To them that ask  where have you seen the Gods  or how do you know for certain there are Gods  that you are so devout in their worship? I answer: Neither have I ever seen my own soul  and yet I respect and honor it."] = None  # 157
d["The foremost art of kings is the power to endure hatred."] = None  # 158
d["Let wickedness escape as it may at the bar  it never fails of doing justice upon itself  for every guilty person is his own hangman."] = None  # 159
d["If thou workest at that which is before thee  following right reason seriously  vigorously  calmly  without allowing anything else to distract thee  but keeping thy divine part pure  as if thou shouldst be bound to give it back immediately  if thou holdest to this  expecting nothing  fearing nothing  but satisfied with thy present activity according to Nature  and with heroic truth in every word and sound which thou utterest  thou wilt live happy. And there is no man who is able to prevent this."] = None  # 160
d["There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will."] = None  # 161
d["Learn how to feel joy."] = None  # 162
d["To live happily is an inward power of the soul."] = None  # 163
d["The happiness of your life depends upon the quality of your thoughts."] = None  # 164
d["Whom they have injured  they also hate."] = None  # 165
d["I often marvel how it is that though each man loves himself beyond all else  he should yet value his own opinion of himself less than that of others."] = None  # 166
d["A hungry people listens not to reason  nor cares for justice  nor is bent by any prayers."] = None  # 167
d["It is often better not to see an insult than to avenge it."] = None  # 168
d["It is often better not to see an insult  than to avenge it."] = None  # 169
d["Accept the things To which fate binds you and Love the people with whom fate Brings you together But do so with all your heart."] = None  # 170
d["Injustice never rules forever."] = None  # 171
d["He who decides a case without hearing the other side  though he decide justly  cannot be considered just."] = None  # 172
d["Men learn while they teach."] = None  # 173
d["Life is a stranger's sojourn  a night at an inn."] = None  # 174
d["The art of living is more like that of wrestling than of dancing. The main thing is to stand firm and be ready for an unforeseen attack."] = None  # 175
d["As is a tale  so is life: not how long it is  but how good it is  is what matters."] = None  # 176
d["True happiness is to understand our duties toward God and man  to enjoy the present  without anxious dependence on the future  not to amuse ourselves with either hopes or fears  but to rest satisfied with what we have  which is abundantly sufficient."] = None  # 177
d["Man is a social animal."] = None  # 178
d["What once were vices are now manners."] = None  # 179
d["Fire tries gold  misery tries brave men."] = None  # 180
d["A good mind possesses a kingdom: a great fortune is a great slavery."] = None  # 181
d["Snow endures but for a season  and joy comes with the morning."] = None  # 182
d["No great thing is created suddenly."] = None  # 183
d["They laboriously do nothing."] = None  # 184
d["It is no easy thing for a principle to become a man's own unless each day he maintains it and works it out in his life."] = None  # 185
d["Do you know that disease and death must needs overtake us  no matter what we are doing? ... What do you wish to be doing when it overtakes you? If you have anything better to be doing when you are so overtaken  get to work on that."] = None  # 186
d["To live each day as though one's last  never flustered  never apathetic  never attitudinizing-here is perfection of character."] = None  # 187
d["Time is a sort of river of passing events  and strong is its current  no sooner is a thing brought to sight than it is swept by and another takes its place  and this too will be swept away."] = None  # 188
d["There is nothing so bitter  that a patient mind cannot find some solace for it."] = None  # 189
d["Nowhere can man find a quieter or more untroubled retreat than in his own soul."] = None  # 190
d["All philosophy lies in two words  sustain and abstain."] = None  # 191
d["Here is the beginning of philosophy: a recognition of the conflicts between men  a search for their cause  a condemnation of mere opinion .. . and the discovery of a standard of judgement."] = None  # 192
d["The happiness of your life depends upon the quality of your thoughts ... take care that you entertain no notions unsuitable to virtue and reasonable nature."] = None  # 193
d["A man's life is what his thoughts make it."] = None  # 194
d["If you wish to live a life free from sorrow  think of what is going to happen as if it had already happened."] = None  # 195
d["He who has great power should use it lightly."] = None  # 196
d["The first petition that we are to make to Almighty God is for a good conscience  the next for health of mind  and then of body."] = None  # 197
d["Revenge is an inhuman word."] = None  # 198
d["This is the chief thing: be not perturbed  for all things are according to the nature of the universal."] = None  # 199
d["Let them know a real man  who lives as he was meant to live."] = None  # 200
d["Do you know that disease and death must needs overtake us  no matter what we are doing? ... What do you wish to be doing when it overtakes you?... If you have anything better to be doing when you are so overtaken  get to work on that."] = None  # 201
d["If you would wish another to keep your secret  first keep it yourself."] = None  # 202
d["Freedom is not procured by a full enjoyment of what is desired  but by controlling that desire."] = None  # 203
d["Ruin and recovery are both from within."] = None  # 204
d["What pulls the strings is the force hidden within  there lies ... the real man."] = None  # 205
d["Look well into thyself  there is a source which will always spring up if thou wilt always search there."] = None  # 206
d["Man must be arched and buttressed from within  else the temple wavers to dust."] = None  # 207
d["How much time he gains who does not look to see what his neighbor says or does or thinks  but only at what he does himself  to make it just and holy."] = None  # 208
d["God has entrusted me with myself."] = None  # 209
d["Nature has given to men one tongue  but two ears  that we may hear from others twice as much as we speak."] = None  # 210
d["Whatever is well said by another  is mine."] = None  # 211
d["First learn the meaning of what you say  and then speak."] = None  # 212
d["Speech is the index of the mind."] = None  # 213
d["Failure changes for the better  success for the worse."] = None  # 214
d["The sun shines even on the wicked."] = None  # 215
d["Never let the future disturb you. You will meet it  if you have to  with the same weapons of reason which today arm you against the present."] = None  # 216
d["It is not the weight of the future or the past that is pressing upon you  but ever that of the present alone. Even this burden  too  can be lessened if you confine it strictly to its own limits."] = None  # 217
d["Everyman's life lies within the present  for the past is spent and done with  and the future is uncertain."] = None  # 218
d["The sole life which a man can lose is that which he is living at the moment."] = None  # 219
d["The passing minute is every man's equal possession but what has once gone by is not ours."] = None  # 220
d["Time discovered truth."] = None  # 221
d["Practice yourself in little things  and thence proceed to greater."] = None  # 222
d["An age builds up cities: an hour destroys them."] = None  # 223
d["Vice can be learnt  even without a teacher."] = None  # 224
d["The sun also shines on the wicked."] = None  # 225
d["There is nothing good or evil save in the will."] = None  # 226
d["Love of bustle is not industry."] = None  # 227
d["If you would be a reader  read  if a writer  write."] = None  # 228
d["All outdoors may be bedlam, provided there is no disturbance within."] = None  # 229
d["We should not moor a ship with one anchor, or our life with one hope."] = None  # 230
d["Neither should a ship rely on one small anchor, nor should life rest on a single hope."] = None  # 231
d["Be careful to leave your sons well instructed rather than rich, for the hopes of the instructed are better than the wealth of the ignorant."] = None  # 232
d["Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart."] = None  # 233
d["Look within. Within is the fountain of good, and it will ever bubble up, if thou wilt ever dig."] = None  # 234
d["Each day provides its own gifts."] = None  # 235
d["When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love."] = None  # 236
d["We have two ears and one mouth so that we can listen twice as much as we speak."] = None  # 237
d["First learn the meaning of what you say, and then speak."] = None  # 238
d["People are not disturbed by things, but by the view they take of them."] = None  # 239
d["Begin - to begin is half the work, let half still remain; again begin this, and thou wilt have finished."] = None  # 240
d["Loss is nothing else but change, and change is Nature's delight."] = None  # 241
d["That which is not good for the bee-hive cannot be good for the bees."] = None  # 242
d["Despise not death, but welcome it, for nature wills it like all else."] = None  # 243
d["It is the nature of the wise to resist pleasures, but the foolish to be a slave to them."] = None  # 244
d["Nothing happens to any man that he is not formed by nature to bear."] = None  # 245
d["Observe constantly that all things take place by change, and accustom thyself to consider that the nature of the Universe loves nothing so much as to change the things which are, and to make new things like them."] = None  # 246
d["Every new beginning comes from some other beginning's end."] = None  # 247
d["Because your own strength is unequal to the task, do not assume that it is beyond the powers of man; but if anything is within the powers and province of man, believe that it is within your own compass also."] = None  # 248
d["Death is a release from the impressions of the senses, and from desires that make us their puppets, and from the vagaries of the mind, and from the hard service of the flesh."] = None  # 249
d["Just as I shall select my ship when I am about to go on a voyage, or my house when I propose to take a residence, so I shall choose my death when I am about to depart from life."] = None  # 250
d["It is not death or pain that is to be dreaded, but the fear of pain or death."] = None  # 251
d["If virtue promises happiness, prosperity and peace, then progress in virtue is progress in each of these for to whatever point the perfection of anything brings us, progress is always an approach toward it."] = None  # 252
d["All religions must be tolerated... for every man must get to heaven in his own way."] = None  # 253
d["Unless we place our religion and our treasure in the same thing, religion will always be sacrificed."] = None  # 254
d["Nothing great is created suddenly, any more than a bunch of grapes or a fig. If you tell me that you desire a fig. I answer you that there must be time. Let it first blossom, then bear fruit, then ripen."] = None  # 255
d["Time is a sort of river of passing events, and strong is its current; no sooner is a thing brought to sight than it is swept by and another takes its place, and this too will be swept away."] = None  # 256
d["How much time he saves who does not look to see what his neighbor says or does or thinks."] = None  # 257
d["The key is to keep company only with people who uplift you, whose presence calls forth your best."] = None  # 258
d["Make the best use of what is in your power, and take the rest as it happens."] = None  # 259
d["To refrain from imitation is the best revenge."] = None  # 260
d["It takes more than just a good looking body. You've got to have the heart and soul to go with it."] = None  # 261
d["We ought to do good to others as simply as a horse runs, or a bee makes honey, or a vine bears grapes season after season without thinking of the grapes it has borne."] = None  # 262
d["Here is the rule to remember in the future, When anything tempts you to be bitter: not, 'This is a misfortune' but 'To bear this worthily is good fortune.'"] = None  # 263
d["The universe is transformation: life is opinion."] = None  # 264
d["A man's worth is no greater than his ambitions."] = None  # 265
d["Let it be your constant method to look into the design of people's actions, and see what they would be at, as often as it is practicable; and to make this custom the more significant, practice it first upon yourself."] = None  # 266
d["Imagine for yourself a character, a model personality, whose example you determine to follow, in private as well as in public."] = None  # 267
d["Aptitude found in the understanding and is often inherited. Genius coming from reason and imagination, rarely."] = None  # 268
d["The art of living is more like wrestling than dancing."] = None  # 269
d["When thou art above measure angry, bethink thee how momentary is man's life."] = None  # 270
d["Friendship always benefits love sometimes injures."] = None  # 271
d["To accuse others for one's own misfortunes is a sign of want of education. To accuse oneself shows that one's education has begun. To accuse neither oneself nor others shows that one's education is complete."] = None  # 272
d["Natural ability without education has more often raised a man to glory and virtue than education without natural ability."] = None  # 273
d["It's not what happens to you, but how you react to it that matters."] = None  # 274
d["He who lives in harmony with himself lives in harmony with the universe."] = None  # 275
d["Very little is needed to make a happy life; it is all within yourself, in your way of thinking."] = None  # 276
d["Execute every act of thy life as though it were thy last."] = None  # 277
d["Begin at once to live, and count each separate day as a separate life."] = None  # 278
d["Forward, as occasion offers. Never look round to see whether any shall note it... Be satisfied with success in even the smallest matter, and think that even such a result is no trifle."] = None  # 279
d["Not every difficult and dangerous thing is suitable for training, but only that which is conducive to success in achieving the object of our effort."] = None  # 280
d["I have often wondered how it is that every man loves himself more than all the rest of men, but yet sets less value on his own opinions of himself than on the opinions of others."] = None  # 281
d["Let men see, let them know, a real man, who lives as he was meant to live."] = None  # 282
d["Men are disturbed not by things, but by the view which they take of them."] = None  # 283
d["Men exist for the sake of one another."] = None  # 284
d["When you are offended at any man's fault, turn to yourself and study your own failings. Then you will forget your anger."] = None  # 285
d["Anger cannot be dishonest."] = None  # 286
d["The universe is change our life is what our thoughts make it."] = None  # 287
d["Is freedom anything else than the right to live as we wish? Nothing else."] = None  # 288
d["Look back over the past, with its changing empires that rose and fell, and you can foresee the future, too."] = None  # 289
d["Enjoy present pleasures in such a way as not to injure future ones."] = None  # 290

# Count
print(f"Placeholders: {len(d)}")