"""Existentialism translations batch 1 (quotes 0-49)."""
import json

with open('c:/Users/lalli/Flutter/coach_phrase_app/missing_exist.json', 'r', encoding='utf-8') as f:
    missing = json.load(f)

tr = {}
batch = missing[:50]

tl = [
    ("Assim falei, cada vez mais suavemente; pois tinha medo dos meus pr\u00f3prios pensamentos e dos pensamentos por tr\u00e1s dos meus pensamentos.", "As\u00ed habl\u00e9, cada vez m\u00e1s suavemente; pues ten\u00eda miedo de mis propios pensamientos y de los pensamientos detr\u00e1s de mis pensamientos."),
    ("Eu s\u00f3 acreditaria num Deus que soubesse dan\u00e7ar.", "Solo creer\u00eda en un Dios que supiera bailar."),
    ("Deixo S\u00edsifo ao p\u00e9 da montanha! Sempre reencontramos nosso fardo. Mas S\u00edsifo ensina a fidelidade superior que nega os deuses e ergue rochas. Ele tamb\u00e9m conclui que tudo est\u00e1 bem. Este universo doravante sem senhor n\u00e3o lhe parece est\u00e9ril nem f\u00fatil. A pr\u00f3pria luta em dire\u00e7\u00e3o aos cumes basta para encher o cora\u00e7\u00e3o de um homem. \u00c9 preciso imaginar S\u00edsifo feliz.", "Dejo a S\u00edsifo al pie de la monta\u00f1a. Siempre reencontramos nuestra carga. Pero S\u00edsifo ense\u00f1a la fidelidad superior que niega a los dioses y levanta rocas. \u00c9l tambi\u00e9n concluye que todo est\u00e1 bien. Este universo en adelante sin amo no le parece est\u00e9ril ni f\u00fatil. La propia lucha hacia las cumbres basta para llenar el coraz\u00f3n de un hombre. Hay que imaginar a S\u00edsifo feliz."),
    ("Todos os erros humanos s\u00e3o impaciência, uma interrup\u00e7\u00e3o prematura do procedimento met\u00f3dico, um aparente cercamento do que aparentemente est\u00e1 em quest\u00e3o.", "Todos los errores humanos son impaciencia, una interrupci\u00f3n prematura del procedimiento met\u00f3dico, un aparente cercamiento de lo que aparentemente est\u00e1 en cuesti\u00f3n."),
    ("Nas vastas extens\u00f5es da noite seca e fria, milhares de estrelas apareciam constantemente, e seus carambelos cintilantes, soltos de uma vez, come\u00e7avam a deslizar gradualmente em dire\u00e7\u00e3o ao horizonte.", "En las vastas extensiones de la noche seca y fr\u00eda, miles de estrellas aparec\u00edan constantemente, y sus carámbanos centelleantes, sueltos de una vez, comenzaban a deslizarse gradualmente hacia el horizonte."),
    ("Como pode um homem se tornar grande se n\u00e3o sente em si a for\u00e7a e a vontade de infligir grande dor?", "\u00bfC\u00f3mo puede un hombre hacerse grande si no siente en s\u00ed la fuerza y la voluntad de infligir gran dolor?"),
    ("Quanto mais ele precisa de Deus, mais profundamente compreende que est\u00e1 necessitado de Deus, e ent\u00e3o quanto mais em sua necessidade avan\u00e7a em dire\u00e7\u00e3o a Deus, mais perfeito ele \u00e9... Precisar de Deus n\u00e3o \u00e9 algo de que se envergonhar, mas \u00e9 a pr\u00f3pria perfei\u00e7\u00e3o.", "Cuanto m\u00e1s necesita a Dios, m\u00e1s profundamente comprende que est\u00e1 necesitado de Dios, y entonces cuanto m\u00e1s en su necesidad avanza hacia Dios, m\u00e1s perfecto es... Necesitar a Dios no es algo de lo que avergonzarse, sino la perfecci\u00f3n misma."),
    ("A f\u00e9 \u00e9 a mais alta paix\u00e3o num ser humano. Muitos em cada gera\u00e7\u00e3o podem n\u00e3o chegar t\u00e3o longe, mas ningu\u00e9m vai al\u00e9m.", "La fe es la m\u00e1s alta pasi\u00f3n en un ser humano. Muchos en cada generaci\u00f3n pueden no llegar tan lejos, pero nadie va m\u00e1s all\u00e1."),
    ("Quando fores \u00e0 mulher, leva teu chicote.", "Cuando vayas a la mujer, lleva tu l\u00e1tigo."),
    ("O que \u00e9 ent\u00e3o a verdade? Um ex\u00e9rcito m\u00f3vel de met\u00e1foras, meton\u00edmias e antropomorfismos; em suma, uma soma de rela\u00e7\u00f5es humanas que foram intensificadas po\u00e9tica e retoricamente, transferidas e adornadas. Verdades s\u00e3o ilus\u00f5es das quais esquecemos que s\u00e3o ilus\u00f5es \u2014 s\u00e3o met\u00e1foras que se desgastaram e perderam sua for\u00e7a sensorial.", "\u00bfQu\u00e9 es entonces la verdad? Un ej\u00e9rcito m\u00f3vil de met\u00e1foras, metonimias y antropomorfismos; en suma, una suma de relaciones humanas que han sido intensificadas po\u00e9tica y ret\u00f3ricamente, transferidas y adornadas. Las verdades son ilusiones de las que hemos olvidado que son ilusiones \u2014 son met\u00e1foras que se han desgastado y perdido su fuerza sensorial."),
    ("Se um homem tem car\u00e1ter, ele tamb\u00e9m tem sua experi\u00eancia t\u00edpica, que sempre se repete.", "Si un hombre tiene car\u00e1cter, tambi\u00e9n tiene su experiencia t\u00edpica, que siempre se repite."),
    ("Melhor um bom jornalista do que um mau assassino.", "Mejor un buen periodista que un mal asesino."),
    ("\u00c9 somente por causa de sua estupidez que eles conseguem ter tanta certeza de si mesmos.", "Es solo por su estupidez que logran estar tan seguros de s\u00ed mismos."),
    ("Ela \u00e9 t\u00e3o distinta para mim, \u00e9 como se eu tivesse passado as m\u00e3os por todo o corpo dela.", "Ella es tan distinta para m\u00ed, es como si hubiera pasado las manos por todo su cuerpo."),
    ("A ess\u00eancia de toda arte bela, de toda grande arte, \u00e9 a gratid\u00e3o.", "La esencia de todo arte bello, de todo gran arte, es la gratitud."),
    ("No meio do inverno, descobri em mim um ver\u00e3o invenc\u00edvel.", "En medio del invierno, descubr\u00ed en m\u00ed un verano invencible."),
    ("Estado \u00e9 o nome do mais frio de todos os monstros frios. Friamente ele mente; e esta mentira escapa de sua boca: 'Eu, o Estado, sou o povo.'", "Estado es el nombre del m\u00e1s fr\u00edo de todos los monstruos fr\u00edos. Fr\u00edamente miente; y esta mentira escapa de su boca: 'Yo, el Estado, soy el pueblo.'"),
    ("Quando os ricos fazem guerra, s\u00e3o os pobres que morrem.", "Cuando los ricos hacen la guerra, son los pobres los que mueren."),
    ("Depois de entrar em contato com um homem religioso, sempre sinto que devo lavar as m\u00e3os.", "Despu\u00e9s de entrar en contacto con un hombre religioso, siempre siento que debo lavarme las manos."),
    ("Aben\u00e7oados s\u00e3o os cora\u00e7\u00f5es que podem se curvar; eles nunca ser\u00e3o quebrados.", "Benditos son los corazones que pueden doblarse; nunca ser\u00e1n quebrados."),
    ("O irracional, a nostalgia humana e o absurdo que nasce de seu encontro \u2014 esses s\u00e3o os tr\u00eas personagens do drama que deve necessariamente terminar com toda a l\u00f3gica de que uma exist\u00eancia \u00e9 capaz.", "Lo irracional, la nostalgia humana y el absurdo que nace de su encuentro \u2014 esos son los tres personajes del drama que debe necesariamente terminar con toda la l\u00f3gica de que una existencia es capaz."),
    ("As rela\u00e7\u00f5es humanas sempre nos ajudam a prosseguir porque sempre pressup\u00f5em desenvolvimentos futuros, um futuro \u2014 e tamb\u00e9m porque vivemos como se nossa \u00fanica tarefa fosse precisamente ter rela\u00e7\u00f5es com outras pessoas.", "Las relaciones humanas siempre nos ayudan a seguir adelante porque siempre presuponen desarrollos futuros, un futuro \u2014 y tambi\u00e9n porque vivimos como si nuestra \u00fanica tarea fuera precisamente tener relaciones con otras personas."),
    ("Na profundidade do inverno, finalmente aprendi que dentro de mim havia um ver\u00e3o invenc\u00edvel.", "En la profundidad del invierno, finalmente aprend\u00ed que dentro de m\u00ed hab\u00eda un verano invencible."),
    ("Uma mulher que sabia que estava bem vestida alguma vez pegou um resfriado?", "\u00bfUna mujer que sab\u00eda que estaba bien vestida alguna vez pesc\u00f3 un resfriado?"),
    ("Muitos s\u00e3o obstinados na busca do caminho que escolheram, poucos na busca do objetivo.", "Muchos son obstinados en la b\u00fasqueda del camino que eligieron, pocos en la b\u00fasqueda del objetivo."),
    ("Se voc\u00ea est\u00e1 solit\u00e1rio quando est\u00e1 sozinho, est\u00e1 em m\u00e1 companhia.", "Si est\u00e1s solitario cuando est\u00e1s solo, est\u00e1s en mala compa\u00f1\u00eda."),
    ("O c\u00edrculo limitado \u00e9 puro.", "El c\u00edrculo limitado es puro."),
    ("Este cora\u00e7\u00e3o dentro de mim eu posso sentir, e julgo que ele existe. Este mundo eu posso tocar, e igualmente julgo que ele existe. A\u00ed termina todo o meu conhecimento, e o resto \u00e9 constru\u00e7\u00e3o. Para sempre serei um estranho para mim mesmo.", "Este coraz\u00f3n dentro de m\u00ed puedo sentirlo, y juzgo que existe. Este mundo puedo tocarlo, e igualmente juzgo que existe. Ah\u00ed termina todo mi conocimiento, y el resto es construcci\u00f3n. Para siempre ser\u00e9 un extra\u00f1o para m\u00ed mismo."),
    ("Um amigo deveria ser mestre em adivinhar e em se calar.", "Un amigo deber\u00eda ser maestro en adivinar y en callar."),
    ("Os homens nunca est\u00e3o realmente dispostos a morrer exceto pela liberdade: portanto n\u00e3o acreditam em morrer completamente.", "Los hombres nunca est\u00e1n realmente dispuestos a morir excepto por la libertad: por lo tanto no creen en morir completamente."),
    ("Fotografamos as coisas para expuls\u00e1-las de nossas mentes. Minhas hist\u00f3rias s\u00e3o uma forma de fechar os olhos.", "Fotografiamos las cosas para expulsarlas de nuestras mentes. Mis historias son una forma de cerrar los ojos."),
    ("O cora\u00e7\u00e3o tem raz\u00f5es que a raz\u00e3o desconhece.", "El coraz\u00f3n tiene razones que la raz\u00f3n desconoce."),
    ("N\u00e3o \u00e9 a for\u00e7a, mas a dura\u00e7\u00e3o dos grandes sentimentos que faz os grandes homens.", "No es la fuerza, sino la duraci\u00f3n de los grandes sentimientos lo que hace a los grandes hombres."),
    ("Para cada homem existe uma isca que ele n\u00e3o pode resistir a engolir.", "Para cada hombre existe un cebo que no puede resistir tragar."),
    ("Para ser feliz, n\u00e3o devemos nos preocupar demais com os outros.", "Para ser feliz, no debemos preocuparnos demasiado con los dem\u00e1s."),
    ("Isto \u00e9 o mais dif\u00edcil de tudo: fechar a m\u00e3o aberta por amor, e manter-se modesto como doador.", "Esto es lo m\u00e1s dif\u00edcil de todo: cerrar la mano abierta por amor, y mantenerse modesto como dador."),
    ("N\u00e3o sei se este mundo tem um significado que o transcende. Mas sei que n\u00e3o posso conhecer esse significado e que me \u00e9 imposs\u00edvel conhec\u00ea-lo agora.", "No s\u00e9 si este mundo tiene un significado que lo trascienda. Pero s\u00e9 que no puedo conocer ese significado y que me es imposible conocerlo ahora."),
    ("O hero\u00edsmo \u00e9 acess\u00edvel. A felicidade \u00e9 mais dif\u00edcil.", "El hero\u00edsmo es accesible. La felicidad es m\u00e1s dif\u00edcil."),
    ("N\u00e3o temos sentimentos que nos mudam, mas sentimentos que nos sugerem a ideia de mudan\u00e7a. Assim, o amor n\u00e3o nos purga do ego\u00edsmo, mas nos torna conscientes dele e nos d\u00e1 a ideia de um pa\u00eds distante onde esse ego\u00edsmo desaparecer\u00e1.", "No tenemos sentimientos que nos cambien, sino sentimientos que nos sugieren la idea de cambio. As\u00ed, el amor no nos purga del ego\u00edsmo, sino que nos hace conscientes de \u00e9l y nos da la idea de un pa\u00eds distante donde ese ego\u00edsmo desaparecer\u00e1."),
    ("Nada \u00e9 mais desprez\u00edvel que o respeito baseado no medo.", "Nada es m\u00e1s despreciable que el respeto basado en el miedo."),
    ("Mate-me, ou voc\u00ea \u00e9 um assassino.", "M\u00e1tame, o eres un asesino."),
    ("Ele provavelmente havia sido expulso de uma taberna, e ainda n\u00e3o tinha ca\u00eddo a ficha.", "Probablemente hab\u00eda sido echado de una taberna, y a\u00fan no se hab\u00eda dado cuenta."),
    ("Melhor n\u00e3o saber nada do que saber muitas coisas pela metade.", "Mejor no saber nada que saber muchas cosas a medias."),
    ("No fim, ama-se o pr\u00f3prio desejo e n\u00e3o o que \u00e9 desejado.", "Al final, uno ama su propio deseo y no lo que es deseado."),
    ("A fun\u00e7\u00e3o da ora\u00e7\u00e3o n\u00e3o \u00e9 influenciar Deus, mas sim mudar a natureza de quem ora.", "La funci\u00f3n de la oraci\u00f3n no es influenciar a Dios, sino cambiar la naturaleza de quien ora."),
    ("Tudo que existe \u00e9 justo e injusto e \u00e9 igualmente justificado em ambos os aspectos.", "Todo lo que existe es justo e injusto y est\u00e1 igualmente justificado en ambos aspectos."),
    ("O que escrevo \u00e9 diferente do que digo, o que digo \u00e9 diferente do que penso, o que penso \u00e9 diferente do que deveria pensar, e assim prossegue at\u00e9 a mais profunda escurid\u00e3o.", "Lo que escribo es diferente de lo que digo, lo que digo es diferente de lo que pienso, lo que pienso es diferente de lo que deber\u00eda pensar, y as\u00ed contin\u00faa hasta la m\u00e1s profunda oscuridad."),
    ("N\u00e3o deveria o doador ser grato porque o receptor recebeu? Dar n\u00e3o \u00e9 uma necessidade? Receber n\u00e3o \u00e9 miseric\u00f3rdia?", "\u00bfNo deber\u00eda el dador estar agradecido porque el receptor recibi\u00f3? \u00bfDar no es una necesidad? \u00bfRecibir no es misericordia?"),
    ("E quando a ampulheta se esgotar, a ampulheta da temporalidade, quando o ru\u00eddo da vida secular se calar e seu ativismo inquieto ou ineficaz tiver chegado ao fim, quando tudo ao seu redor estiver quieto, como na eternidade, ent\u00e3o a eternidade lhe pergunta sobre apenas uma coisa: se voc\u00ea viveu em desespero ou n\u00e3o.", "Y cuando el reloj de arena se haya agotado, el reloj de arena de la temporalidad, cuando el ruido de la vida secular se haya callado y su activismo inquieto o ineficaz haya llegado a su fin, cuando todo a tu alrededor est\u00e9 quieto, como en la eternidad, entonces la eternidad te pregunta sobre solo una cosa: si viviste en desesperaci\u00f3n o no."),
]

for i, key in enumerate(batch):
    if i < len(tl):
        tr[key] = {"pt": tl[i][0], "es": tl[i][1]}

with open('c:/Users/lalli/Flutter/coach_phrase_app/translations_exist.json', 'w', encoding='utf-8') as f:
    json.dump(tr, f, ensure_ascii=False, indent=2)

print(f'Existentialism batch 1: {len(tr)} translations')
