"""Add final 18 missing stoicism translations using exact keys from missing_stoic.json."""
import json

with open('c:/Users/lalli/Flutter/coach_phrase_app/missing_stoic.json', 'r', encoding='utf-8') as f:
    missing = json.load(f)

with open('c:/Users/lalli/Flutter/coach_phrase_app/translations_stoicism.json', 'r', encoding='utf-8') as f:
    tr = json.load(f)

# Translations for each of the 18 missing quotes (using exact keys)
translations = [
    {"pt": "Quando um jovem se exibia no Teatro dizendo: \u2018Sou s\u00e1bio, pois conversei com muitos homens s\u00e1bios\u2019, Epicteto respondeu: \u2018Eu tamb\u00e9m conversei com muitos homens ricos, mas n\u00e3o sou rico!\u2019.",
     "es": "Cuando un joven se pavoneaba en el Teatro diciendo: \u2018Soy sabio, pues he conversado con muchos hombres sabios\u2019, Epicteto respondi\u00f3: \u2018\u00a1Yo tambi\u00e9n he conversado con muchos hombres ricos, pero no soy rico!\u2019."},
    {"pt": "Nada, a meu ver, \u00e9 uma prova melhor de uma mente bem ordenada do que a capacidade de um homem de parar exatamente onde est\u00e1 e passar algum tempo em sua pr\u00f3pria companhia.",
     "es": "Nada, a mi parecer, es una mejor prueba de una mente bien ordenada que la capacidad de un hombre de detenerse justo donde est\u00e1 y pasar un tiempo en su propia compa\u00f1\u00eda."},
    {"pt": "N\u00e3o sou um \u2018homem s\u00e1bio\u2019, nem... jamais serei. Portanto, n\u00e3o exija de mim que eu seja igual aos melhores, mas que eu seja melhor que os maus. \u00c9 suficiente para mim se todos os dias eu reduzir o n\u00famero dos meus v\u00edcios e censurar meus erros.",
     "es": "No soy un \u2018hombre sabio\u2019, ni... jam\u00e1s lo ser\u00e9. Por lo tanto, no exijas de m\u00ed que sea igual a los mejores, sino que sea mejor que los malvados. Es suficiente para m\u00ed si cada d\u00eda reduzco el n\u00famero de mis vicios y censuro mis errores."},
    {"pt": "Sobre os Deuses, h\u00e1 os que negam a pr\u00f3pria exist\u00eancia da Divindade; outros dizem que ela existe, mas n\u00e3o se move nem se preocupa com nada. Um terceiro grupo atribui a ela exist\u00eancia e provid\u00eancia, mas apenas para assuntos grandes e celestiais, n\u00e3o para nada na terra. Um quarto grupo admite coisas na terra e no c\u00e9u, mas apenas em geral. Um quinto, do qual faziam parte Ulisses e S\u00f3crates, s\u00e3o os que clamam: N\u00e3o me movo sem Teu conhecimento!",
     "es": "Sobre los Dioses, hay quienes niegan la existencia misma de la Divinidad; otros dicen que existe, pero no se mueve ni se preocupa por nada. Un tercer grupo le atribuye existencia y providencia, pero solo para asuntos grandes y celestiales, no para nada en la tierra. Un cuarto grupo admite cosas en la tierra y en el cielo, pero solo en general. Un quinto, del que formaban parte Ulises y S\u00f3crates, son los que claman: \u00a1No me muevo sin Tu conocimiento!"},
    {"pt": "Quando voc\u00ea entra numa floresta povoada por \u00e1rvores antigas, mais altas que o comum, cobrindo o c\u00e9u com seus galhos densamente entrecruzados, n\u00e3o o impressionam as sombras majestosas do bosque, a quietude do lugar e a tremenda escurid\u00e3o desta caverna com a presen\u00e7a de uma divindade?",
     "es": "Cuando entras en un bosque poblado de \u00e1rboles antiguos, m\u00e1s altos de lo com\u00fan, cubriendo el cielo con sus ramas densamente entrelazadas, \u00bfno te impresionan las sombras majestuosas del bosque, la quietud del lugar y la tremenda oscuridad de esta caverna con la presencia de una divinidad?"},
    {"pt": "Como \u00e9 bom, quando tem carne assada ou alimentos semelhantes diante de voc\u00ea, imprimir em sua mente que isto \u00e9 o corpo morto de um peixe, isto \u00e9 o corpo morto de uma ave ou porco; e ainda, que o vinho Falerno \u00e9 mero suco de uvas, e sua toga de borda p\u00farpura simplesmente o pelo de uma ovelha embebido em sangue de molusco! Qu\u00e3o boas s\u00e3o essas percep\u00e7\u00f5es para chegar ao cora\u00e7\u00e3o da coisa real. A vaidade \u00e9 a maior sedutora da raz\u00e3o: quando voc\u00ea est\u00e1 mais convicto de que seu trabalho \u00e9 importante, \u00e9 quando est\u00e1 mais sob seu feiti\u00e7o.",
     "es": "Qu\u00e9 bueno es, cuando tienes carne asada o alimentos semejantes ante ti, imprimir en tu mente que esto es el cuerpo muerto de un pez, esto es el cuerpo muerto de un ave o cerdo; y adem\u00e1s, que el vino Falerno es mero jugo de uvas, y tu toga de borde p\u00farpura simplemente el pelo de una oveja empapado en sangre de molusco. La vanidad es la mayor seductora de la raz\u00f3n: cuando est\u00e1s m\u00e1s convencido de que tu trabajo es importante, es cuando est\u00e1s m\u00e1s bajo su hechizo."},
    {"pt": "Que necessidade de dica ou sugest\u00e3o quando cabe a voc\u00ea discernir o que precisa ser feito \u2014 e, se pode ver o caminho, segui-lo com inten\u00e7\u00e3o gentil mas inabal\u00e1vel. Se n\u00e3o pode ver o caminho, recue e consulte seus melhores conselheiros. A justi\u00e7a \u00e9 o melhor objetivo, pois qualquer falha \u00e9 de fato uma falha de justi\u00e7a. Um homem que segue a raz\u00e3o em tudo combina relaxamento com iniciativa, \u00edmpeto com compostura.",
     "es": "Qu\u00e9 necesidad de pista o sugerencia cuando te corresponde discernir lo que necesita hacerse \u2014 y, si puedes ver el camino, seguirlo con intenci\u00f3n gentil pero inquebrantable. Si no puedes ver el camino, ret\u00edrate y consulta a tus mejores consejeros. La justicia es el mejor objetivo, pues cualquier falla es de hecho una falla de justicia. Un hombre que sigue la raz\u00f3n en todo combina relajaci\u00f3n con iniciativa, \u00edmpetu con compostura."},
    {"pt": "Voc\u00ea deve estar sempre pronto para aplicar duas regras de a\u00e7\u00e3o: a primeira, n\u00e3o fazer nada al\u00e9m do que a arte real e legislativa ordena para o benef\u00edcio da humanidade; a segunda, estar preparado para mudar de opini\u00e3o se algu\u00e9m estiver \u00e0 m\u00e3o para corrigi-lo e gui\u00e1-lo para longe de alguma opini\u00e3o infundada.",
     "es": "Debes estar siempre listo para aplicar dos reglas de acci\u00f3n: la primera, no hacer nada m\u00e1s que lo que el arte real y legislativo ordena para el beneficio de la humanidad; la segunda, estar preparado para cambiar de opini\u00f3n si alguien est\u00e1 a mano para corregirte y guiarte lejos de alguna opini\u00f3n infundada."},
    {"pt": "N\u00e3o s\u00e3o as a\u00e7\u00f5es dos outros que nos perturbam (pois essas a\u00e7\u00f5es s\u00e3o controladas por sua parte governante), mas sim nossos pr\u00f3prios julgamentos. Portanto, remova esses julgamentos e resolva abandonar sua raiva, e ela j\u00e1 ter\u00e1 ido embora. Como se abandona? Percebendo que tais a\u00e7\u00f5es n\u00e3o s\u00e3o vergonhosas para voc\u00ea.",
     "es": "No son las acciones de los dem\u00e1s las que nos perturban (pues esas acciones son controladas por su parte gobernante), sino m\u00e1s bien nuestros propios juicios. Por lo tanto, elimina esos juicios y resuelve soltar tu ira, y ya se habr\u00e1 ido. \u00bfC\u00f3mo se suelta? Dando cuenta de que tales acciones no son vergonzosas para ti."},
    {"pt": "Que tudo \u00e9 como o pensamento faz \u2014 e voc\u00ea controla seu pensamento. Ent\u00e3o remova seus julgamentos quando quiser e haver\u00e1 calma \u2014 como o marinheiro contornando o cabo encontra \u00e1guas calmas e a acolhida de uma ba\u00eda sem ondas.",
     "es": "Que todo es como el pensamiento lo hace \u2014 y t\u00fa controlas tu pensamiento. Entonces elimina tus juicios cuando quieras y habr\u00e1 calma \u2014 como el marinero que rodea el cabo encuentra aguas tranquilas y la acogida de una bah\u00eda sin olas."},
    {"pt": "O mundo que voc\u00ea v\u00ea, a maior e mais gloriosa cria\u00e7\u00e3o da natureza, e a mente humana que a contempla e se maravilha, e \u00e9 a parte mais espl\u00eandida dela, essas s\u00e3o nossas posses eternas e permanecer\u00e3o conosco enquanto n\u00f3s mesmos permanecermos. Ent\u00e3o, \u00e1vidos e corretos, apressemo-nos com passos ousados aonde quer que as circunst\u00e2ncias nos levem: n\u00e3o pode haver lugar de ex\u00edlio no mundo, j\u00e1 que nada no mundo \u00e9 alheio aos homens.",
     "es": "El mundo que ves, la mayor y m\u00e1s gloriosa creaci\u00f3n de la naturaleza, y la mente humana que la contempla y se maravilla, y es la parte m\u00e1s espl\u00e9ndida de ella, esas son nuestras posesiones eternas y permanecer\u00e1n con nosotros mientras nosotros mismos permanezcamos. Entonces, \u00e1vidos y rectos, apresurémonos con pasos audaces adonde las circunstancias nos lleven: no puede haber lugar de exilio en el mundo, ya que nada en el mundo es ajeno a los hombres."},
    {"pt": "At\u00e9 quando vai esperar antes de exigir o melhor de si mesmo? Voc\u00ea recebeu os princ\u00edpios que deveria endossar, e os endossou. Que tipo de professor voc\u00ea ainda est\u00e1 esperando? Voc\u00ea n\u00e3o \u00e9 mais um menino, mas um homem adulto. Se for descuidado e pregui\u00e7oso agora, viver\u00e1 e morrer\u00e1 como algu\u00e9m comum. A partir de agora, resolva viver como um adulto que progride. Foi assim que S\u00f3crates se realizou. E voc\u00ea, embora n\u00e3o seja um S\u00f3crates, deveria viver como algu\u00e9m que ao menos quer ser um S\u00f3crates.",
     "es": "\u00bfHasta cu\u00e1ndo vas a esperar antes de exigir lo mejor de ti mismo? Has recibido los principios que deb\u00edas respaldar, y los has respaldado. \u00bfQu\u00e9 tipo de maestro sigues esperando? Ya no eres un ni\u00f1o, sino un hombre adulto. Si eres descuidado y perezoso ahora, vivir\u00e1s y morir\u00e1s como alguien com\u00fan. Desde ahora, resuelve vivir como un adulto que progresa. As\u00ed fue como S\u00f3crates se realiz\u00f3. Y t\u00fa, aunque no seas un S\u00f3crates, deber\u00edas vivir como alguien que al menos quiere ser un S\u00f3crates."},
    {"pt": "O \u00eanxtase sexual \u00e9 como a morte. \u00c9 um dos segredos da sabedoria da natureza.",
     "es": "El \u00e9xtasis sexual es como la muerte. Es uno de los secretos de la sabidur\u00eda de la naturaleza."},
    {"pt": "Todas as maiores b\u00ean\u00e7\u00e3os s\u00e3o fonte de ansiedade, e em nenhum momento a fortuna deve ser menos confiada do que quando est\u00e1 no melhor. Pois tudo que nos vem do acaso \u00e9 inst\u00e1vel, e quanto mais alto sobe, mais propenso \u00e9 a cair. Al\u00e9m disso, o que est\u00e1 fadado a perecer n\u00e3o traz prazer a ningu\u00e9m.",
     "es": "Todas las mayores bendiciones son fuente de ansiedad, y en ning\u00fan momento la fortuna debe ser menos confiada que cuando est\u00e1 en su mejor momento. Pues todo lo que nos viene del azar es inestable, y cuanto m\u00e1s alto sube, m\u00e1s propenso es a caer. Adem\u00e1s, lo que est\u00e1 destinado a perecer no trae placer a nadie."},
    {"pt": "N\u00e3o \u00e9 que tenhamos pouco tempo, mas que desperdi\u00e7amos muito dele. A vida \u00e9 longa o suficiente, e foi dada em medida suficientemente generosa para permitir a realiza\u00e7\u00e3o das maiores coisas, se toda ela for bem investida. Mas quando \u00e9 esbanjada em luxo e descuido, quando n\u00e3o \u00e9 dedicada a nenhum bom fim, percebemos que ela passou antes de percebermos que estava passando.",
     "es": "No es que tengamos poco tiempo, sino que desperdiciamos mucho de \u00e9l. La vida es lo suficientemente larga, y ha sido dada en medida suficientemente generosa para permitir el logro de las cosas m\u00e1s grandes, si toda ella se invierte bien. Pero cuando se desperdicia en lujo y descuido, cuando no se dedica a ning\u00fan buen fin, percibimos que ha pasado antes de darnos cuenta de que estaba pasando."},
    {"pt": "...certas pessoas t\u00eam sangue bom e comum, e outras t\u00eam um tipo de sangue animado e vivo que sobe ao rosto rapidamente.",
     "es": "...ciertas personas tienen sangre buena y com\u00fan, y otras tienen un tipo de sangre animada y viva que sube al rostro r\u00e1pidamente."},
    {"pt": "A leitura deve servir ao objetivo de alcan\u00e7ar a paz; se n\u00e3o o torna pac\u00edfico, para que serve?",
     "es": "La lectura debe servir al objetivo de alcanzar la paz; si no te hace pac\u00edfico, \u00bfde qu\u00e9 sirve?"},
    {"pt": "Que seja seu m\u00e9todo constante examinar o desígnio das a\u00e7\u00f5es das pessoas, e ver o que desejam, com a frequ\u00eancia que for pratic\u00e1vel; e para tornar esse costume mais significativo, pratique-o primeiro consigo mesmo.",
     "es": "Que sea tu m\u00e9todo constante examinar el designio de las acciones de las personas, y ver qu\u00e9 desean, con la frecuencia que sea practicable; y para hacer esta costumbre m\u00e1s significativa, pract\u00edcala primero contigo mismo."},
]

for key, trans in zip(missing, translations):
    tr[key] = trans

with open('c:/Users/lalli/Flutter/coach_phrase_app/translations_stoicism.json', 'w', encoding='utf-8') as f:
    json.dump(tr, f, ensure_ascii=False, indent=2)

print(f'Total stoicism translations: {len(tr)}')
print(f'Added {len(translations)} final translations')
